name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      # --- CHECKOUT -----------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # --- GO SETUP -----------------------------------------------------
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      # --- VERSIONING ---------------------------------------------------
      - name: Generate version
        id: version
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          COUNT=$(git rev-list --count HEAD --since="$(date +%Y-%m-01)")
          VERSION="$YEAR.$MONTH.$COUNT"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "$VERSION" > version.txt

      - name: Show version
        run: |
            echo "ðŸ“Œ Version: ${{ steps.version.outputs.version }}"

      # --- TESTING ------------------------------------------------------
      - name: Run tests
        run: go test -v ./...

      # --- LINTING ------------------------------------------------------
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run linters
        run: |
          gofmt -l .
          golangci-lint run ./...

      # --- BUILD GO BINARY ----------------------------------------------
      - name: Build with version
        run: |
          go build -ldflags "-X github.com/MrBoggi/goTOV/internal/version.Version=${{ steps.version.outputs.version }}" \
            -o bin/gotov ./cmd/gotov/

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-version
          path: version.txt

      # --- DOCKER LOGIN -------------------------------------------------
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- DOCKER BUILD -------------------------------------------------
      - name: Build Docker image
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"

          docker build \
            -t ghcr.io/$OWNER_LC/gotov:latest \
            -t ghcr.io/$OWNER_LC/gotov:${{ steps.version.outputs.version }} .

      # --- DOCKER PUSH --------------------------------------------------
      - name: Push Docker image
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"

          docker push ghcr.io/$OWNER_LC/gotov:latest
          docker push ghcr.io/$OWNER_LC/gotov:${{ steps.version.outputs.version }}

        # --- CHANGELOG GENERATION -----------------------------------------
      - name: Generate changelog with git-cliff
        uses: orhun/git-cliff-action@v3
        id: cliff
        with:
          config: cliff.toml
          args: --latest

